[BUG] 인증된 사용자 로그인, 회원가입 요청 처리
CokeLee777/spring-security-jwt-auth pull request #28
Opened 2023-05-31 05:46 UTC by CokeLee777

1. 로그인, 회원가입 요청을 이미 인증된 사용는 요청이 불가능하게끔 처리
2. 홈 화면은 모든 사용자가 접근 가능하도록 처리

2023-05-31 10:55 UTC, JSY8869 requested changes
리뷰 확인 후 코멘트 부탁드립니다~

2023-05-31 10:55 UTC, JSY8869 commented on src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
> +    private boolean isAuthorized() {
아래 부분에서 로그인 후 다시 로그인 요청을 하여도 securityContext와 authentication이 null 값이 나오던데 확인 부탁드립니다!

2023-05-31 10:55 UTC, JSY8869 commented on src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
> +        return authentication.getClass().equals(JwtAuthenticationToken.class);
이거 이렇게 비교하면 항상 false가 나오지 않나요? 확인 부탁드립니다!

2023-06-01 01:54 UTC, CokeLee777 commented on src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
> +    private boolean isAuthorized() {
로그인 후 클라이언트는 헤더에 엑세스 토큰과 쿠키에 리프레쉬 토큰을 넣어서 요청하게 되는데, 이렇게 되면 AuthorizationFilter에서 시큐리티 컨텍스트에 인증 객체를 넣어서 다음 필터인 현재 필터로 이동하게 되므로 null 값이 나오지 않습니다. 다시 확인해주세요

2023-06-01 03:09 UTC, JSY8869 commented on src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
> +    private boolean isAuthorized() {
아 로그인 후 토큰을 넣어서 로그인을 요청하는 경우를 본거군요. 확인 했습니다!

2023-06-01 03:38 UTC, CokeLee777 commented on src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
> +        return authentication.getClass().equals(JwtAuthenticationToken.class);
로그인 했을때 헤더에 엑세스 토큰을 넣지 않고 요청한것같으니 다시 확인해주세요.

2023-06-01 04:04 UTC, JSY8869 approved these changes

2023-06-01 04:04 UTC, JSY8869 commented on src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
> +        return authentication.getClass().equals(JwtAuthenticationToken.class);
확인했습니다~

2023-06-01 04:05 UTC, merged